version: "3.9"
services:
  backend:
    build:
      context: ./ecom-project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./ecom-front/ecom-catalog-react
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
